project:
  type: website

website:
  title: "Website/Dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Dashboard
        href: dashboard.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
