project:
  type: website

website:
  title: "demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true

filters:
  - title-dropdown.lua
title-dropdown:
  - text: "Home"
    href: "index.html"
  - text: "About"
    href: "about.html"
