project:
  type: website

website:
  title: "demo"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Preview** "
    type: danger
  navbar:
    left:
      - text: "This is not Home"
        href: about.qmd
format:
  html:
    theme:
      - vapor
      - brand
    css: styles.css
