project:
  type: website

website:
  title: "demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: questions.qmd
        text: Questions
      - href: answers.qmd
        text: Answers

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
