project:
  type: website

website:
  title: "Broken between 1.4.533 and 1.4.534"
  navbar:
    left:
      - href: index.qmd
        text: Solana
      - href: broadside.qmd
        text: Broadside
      - href: trestles.qmd
        text: Trestles
      - href: jolla.qmd
        text: Jolla
      - href: solana.qmd
        text: Solana
      - href: marquee.qmd
        text: Marquee

format:
  html:
    theme: cosmo
    toc: true
