project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll

pagetitle: "{{< meta title >}}"

website:
  title: "The Gilpatrick"
  favicon: thegilpatricklogo.png
  open-graph: true
  twitter-card: true
  cookie-consent: 
    type: express
    style: headline
    palette: light
  google-analytics: 
    tracking-id: "G-Y5TZ8D5H35"
    anonymize-ip: true
  site-url: https://m.canouil.dev/quarto-issue5973/
  navbar:
    right:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/thegilpatrick/thegilpatrick.github.io
          - text: Report a Bug
            url:  https://github.com/thegilpatrick/thegilpatrick.github.io/issues
    logo: thegilpatricklogo.png
    logo-alt: "The Gilpatrick logo."
    title: false
    background: white
    left:
      - text: "About"
        file: about.qmd
format:
  html:
    include-after-body: subscribe.html
    theme: cosmo
    css: styles.css

execute:
  freeze: auto
